CREATE TABLE IF NOT EXISTS group_name(
    ID INT PRIMARY KEY NOT NULL,
    IMAGE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    MEMBERS TEXT[] NOT NULL,
    CREATION_DATE INT NOT NULL,
    FIRST_ALBUM VARCHAR(50),
    LOCATIONS TEXT NOT NULL,
    CONCERT_DATES TEXT NOT NULL,
    RELATIONS TEXT NOT NULL
);